### ISSUE TITLE
Valet home directory is inside /root

### ISSUE THREAD

**Issue by geradrum** [cpriego/valet-linux#33] opened 2017-03-12 05:09 UTC
I'm trying to install valet but I've got and exception

```
[RuntimeException]
Valet home directory is inside /root

install [--ignore-selinux]
```

I installed antergos 1 week ago and it was working, no problems but then I reinstalled antergos 3 days ago and same error, I didn't change anything in the system or installation. Now I just installed Arch and same error.

**Comment by cpriego** [comment] 2017-03-12 06:17
That exception is by design. You should not run Valet as root. It must be run with a sudo user with the $HOME environment set. It is in the readme https://github.com/cpriego/valet-linux#fedora

**Comment by acalzada** [comment] 2017-03-13 18:37
I've downloaded _valet-linux_ into my RaspBerry Pi (Raspbian) as the default _pi_ user.
```
pi@raspberrypi:~ $ composer global require cpriego/valet-linux
Changed current directory to /home/pi/.config/composer
Using version ^2.0 for cpriego/valet-linux
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
pi@raspberrypi:~ $ 
```

The _pi_ user has it's own _$HOME_ directory (/home/pi) and also is a _sudoer_.
However when I run `valet install` I get the same error:
```
  pi@raspberrypi:~ $ valet install 

  [RuntimeException]                    
  Valet home directory is inside /root  

  install [--ignore-selinux]

  pi@raspberrypi:~ $
```

Any clues how to solve it?
Thanks

**Comment by TheNodi** [comment] 2017-03-13 23:39
If you run the command `sudo echo $HOME` and the output is `/root` try to follow the fedora instructions:

> To set the $HOME environment variable when using sudo in Fedora:
> - Open your sudoers file with `visudo`
> - Find the lines with the text `Defaults env_keep +=`
> - Append `Defaults env_keep += "HOME"` after those lines
> - Save your changes

**Comment by semencov** [comment] 2017-03-23 14:01
Hi. I have Debian *jessie* and there is the same issue. The main problem is cause by this part in bash script:

```sh
# If the command is one of the commands that requires "sudo" privileges
# then we'll proxy the incoming CLI request using sudo, which allows
# us to never require the end users to manually specify each sudo.
if [[ -n $1 && $SUDOCMDS =~ $1 ]]
then
    if [[ "$EUID" -ne 0 ]]
    then
        sudo $SOURCE "$@"
        exit
    fi
fi
```

So if trying to run `valet install` w/o `sudo` it will run it through `sudo` anyway, so PHP's `$_SERVER['HOME'] which is user in `cli/includes/helpers.php` to define `VALET_HOME_PATH` will have value `/root`.

[Visudo method](https://github.com/cpriego/valet-linux/issues/33#issuecomment-286277418) does not work in my case.

**Comment by geradrum** [comment] 2017-03-23 14:42
@semencov Visudo didn't worked for me either, instead I edited the /etc/sudoers file directly and it worked, I faced some problems after that like php-fpm and nginx were not running and do some config for dnsmasq but now all works just fine.

**Comment by semencov** [comment] 2017-03-23 15:02
@geradrum, `visudo` do exactly the same — edits the sudoers file. I meant that the changes in the sudoers did not help me. I believe PHP takes home folder not from the environment.

**Comment by TheNodi** [comment] 2017-03-23 15:20
I think it should actually be taking those variables from the environment (on a command line execution):
```
$ export SOME_VARIABLE=helloworld
$ php -r 'echo $_SERVER["SOME_VARIABLE"];'
helloworld
$ echo $SOME_VARIABLE
helloworld
$ unset SOME_VARIABLE
$ echo $SOME_VARIABLE

$ php -r 'echo $_SERVER["SOME_VARIABLE"];'
PHP Notice:  Undefined index: SOME_VARIABLE in Command line code on line 1
```

If you try to run the following command without sudo, does it show the correct home path?
```
$ php -r 'echo $_SERVER["HOME"];'
```

**Comment by semencov** [comment] 2017-03-24 07:39
@TheNodi sure it shows correct path without the `sudo`.

```sh
yuri ~ ❯ php -r 'echo $_SERVER["HOME"];'
/home/yuri
yuri ~ ❯ sudo php -r 'echo $_SERVER["HOME"];'
/root
```
Well sure some variables PHP takes from environment, however I believe some vars related to user PHP gets from other sources. And here is why I think so: with all that `visudo` settings (btw, there are also `set_home` and `always_set_home` options) bash just works fine and inherits environment as well as the `$HOME` of sudoer, but PHP still shows HOME as for root user even with `-E` or `-H` arguments passed to `sudo` (which are for preserving environment and home path respectively).

```sh
yuri ~ ❯ sudo echo $HOME
/home/yuri
yuri ~ ❯ sudo php -r 'echo $_SERVER["HOME"];'
/root
yuri ~ ❯ sudo -H php -r 'echo $_SERVER["HOME"];'
/root
yuri ~ ❯ sudo -E php -r 'echo $_SERVER["HOME"];'
/root
```

**Comment by TheNodi** [comment] 2017-03-24 16:08
If you use the `-H` flag it sets the home to the final user's home (root user in this case), overriding any settings.

I'm not able to reproduce it. Can you share your `/etc/sudoers` file?

**Comment by semencov** [comment] 2017-03-25 14:19
Here it is:

```sh
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults	env_reset
Defaults	mail_badpass
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
Defaults  env_keep +="SSH_CLIENT SSH_CONNECTION SSH_TTY SSH_AUTH_SOCK PATH HOME"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root	ALL=(ALL:ALL) ALL
yuri	ALL=(ALL:ALL) NOPASSWD:ALL

# Allow members of group sudo to execute any command
%sudo	ALL=(ALL:ALL) NOPASSWD:ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
```

**Comment by TheNodi** [comment] 2017-03-25 16:05
With the same sudoers file `$HOME` is passed, PHP7 is reading it and valet is working just fine to me.

Can you share the results of the following commands?
```
lsb_release -a
php -v
```
It should be on the php-side of things since $HOME was kept correctly. Have you maybe edited your `php.ini`?

If you do something like this, does it work?
```
$ HOME=helloworld php -r 'echo $_SERVER["HOME"];'
helloworld
```

I'm gonna re-open the issue to see if someone has more luck than me reproducing the issue.

Pinging @cpriego

**Comment by cpriego** [comment] 2017-03-26 21:21
@geradrum @TheNodi 

Ok, so I just downloaded and spinned up a new Debian Jessie VM to test this. Here is my experience:
1. At first my user was **not** in the `sudo` group. I had to add it to it.
2. I installed the php version from de Debian repos (5.6) and composer. No problems so far.
3. I required cpriego/valet-linux: `composer global require cpriego/valet-linux`
4. Since I didn't add the composer global bin to my path I executed valet directly with `~/.config/composer/vendor/bin/valet install`
5. I **got** the **`Valet home directory is inside /root`** error.
![selection_007](https://cloud.githubusercontent.com/assets/6462826/24334964/c545175c-1231-11e7-84b3-bacb869dd4ca.png)
6. To fix it I simply followed the instructions in the [wiki](https://github.com/cpriego/valet-linux/wiki/Sudo-and-the-HOME-Environment-Variable) adding the lines right **after** all the lines saying `Defaults`
![selection_006](https://cloud.githubusercontent.com/assets/6462826/24334971/df56221c-1231-11e7-8501-fe310ed79d25.png)
7. Problem is fixed and I am able to install valet.
![selection_008](https://cloud.githubusercontent.com/assets/6462826/24334973/e7ff1824-1231-11e7-81ee-a7b03bcf453e.png)

So I'm not able to reproduce this particular bug. What I noticed is Debian is different to all the other distros so valet fails to install some config files. Debian is not officially supported for now but I'll look into this issues to support it.

Try putting the `Defaults env_keep +="HOME"` in a separate line to see if that fixes your issue.

**Comment by cpriego** [comment] 2017-03-26 21:30
Finally! I was able to successfully install valet in Debian (man, the installed packages and defaults are so different). In Debian you have to install `resolvconf dnsmasq-base` and uninstall `dnsmasq`. Also you have to manually create the `/etc/NetworkManager/dnsmasq.d` directory. After that you can `valet install` then `valet park` your projects folder and it will work.

I don't know what the best approach is since the changes in the case of debian are very disruptive. Maybe just adding a Debian guide in the wiki will suffice?

**Comment by semencov** [comment] 2017-03-27 07:43
Here it is (it is not really Debian, but it based on):

```sh
yuri ~ ❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Deepin
Description:	Deepin 15.3
Release:	15.3
Codename:	unstable

yuri ~ ❯ php -v
PHP 7.0.17-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.17-1~dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies
```

Putting `Defaults env_keep +="HOME"` on the separate line didn't help.

**Comment by cpriego** [comment] 2017-03-29 20:16
Hi @semencov, I tried to use Deepin 15.3 in a virtual environment but it had a plethora of issues, requires a lot of resources and it has a ton of pending updates. Before installing a single package the whole update process ended in a kernel panic mess and I was unable to even setup the environment for testing.

I'll give it another run but if problems persist and there is no one else who can reproduce this issue I'm afraid I'll have to close this issue as there is no apparent solution to it and that points to an incompatibility with your specific installation.

**Comment by cpriego** [comment] 2017-03-29 23:19
@semencov

This time I was successful. I was able to test the environment and discovered that for some reason Deepin never passes the `$HOME` env variable when using sudo. I tried the workaround described above with success. This allowed me to discover other quirks with Deepin and to fix them. Please test these changes installing the master version.

Simple way:
```
composer global remove "cpriego/valet-linux" && composer global require "cpriego/valet-linux:dev-master"
```

**Comment by geradrum** [comment] 2017-03-30 01:03
@cpriego Thanks for your help, I was able to install valet modifying the sudoers file but I had some problems, after install valet I wasn't able to start it....

`valet status` was returning 

```
Php-fpm is not running...
Nginx is not running...
```

PHP-FPM and Nginx were installed but for some reason they're weren't running.
So, I executed `sudo php-fpm` and `sudo nginx`, npm was fine but fpm couldn't start and I was getting this message:

```
ERROR: [pool valet] cannot get gid for user 'gerardo'
```

After some research all I had to do was modify the `php-fpm.conf` file and add a group.
I restarted fpm and tried to open a `.dev` domain and now I was able to see the typical 404 from valet. To solve that I just uninstalled dnsmasq, reinstalled valet, restarted dnsmasq service and finally valet is working...
It took me like 2 days to solve this, I'm using Antergos and also tried on Arch, both clean installations and I had the exact same problem.
I'll try to reproduce this same behavior on another machine and post a solution if anyone needs it.

**Comment by cpriego** [comment] 2017-03-30 06:07
Hola @geradrum muchas gracias por tu apoyo, mis pruebas las corrí en Manjaro así que podría haber ligeras diferencias con respecto a Arch/Antergos. Sería de muchas ayuda darle un seguimiento más profundo a tu problema.

Como podrás ver hice unos cambios recientemente al código. Por favor desinstala por completo las versiones anteriores con `valet uninstall` y luego eliminando el paquete con composer y reinstalando la rama `master` tal y como se lo pedi **semencov**.

¿Podrías abrir un nuevo issue aquí mismo con un título como "PHP-FPM fails to start"? Esto para que si el problema de /root quedó resuelto pueda cerrar este issue y trabajar el problema de php-fpm a detalle.

**Comment by geradrum** [comment] 2017-03-30 23:45
@cpriego claro que sí. Lo hubiera escrito en español para dar mas detalles.
El problema que tengo en Antergos y Arch es el de este mismo issue, pero con las instrucciones que me proporcionaste para fedora (descomentando la linea `Defaults env_keep +="HOME"`) la instalación continua perfectamente, pero a la hora abrir cualquier dominio `.dev` Chrome me tira el error de ERR ICANN NAME COLLISION lo que quiere decir que los DNS no están funcionando, al igual que php-fpm y nginx no están corriendo. Lo que se me hace algo raro es que la primera vez que instalé Antergos de manera limpia la instalación de valet funcionó sin ningún problema y se ejecutó como debería ser, al reinstalar Antergos (igual limpio, eliminando y formateando particiones) comenzó este error. Instalé Arch para comprobar que no sucediera el mismo error, pero no, paso exactamente lo mismo, `php-fpm`, `nginx` y `dnsmasq` se instalan al ejecutar `valet install` via pacman pero no se ejecutan.

**Comment by cpantu** [comment] 2017-04-02 16:18
@cpriego The master branch works great in Deepin 15.3 

Thanks Great Work!

**Comment by semencov** [comment] 2017-04-04 09:41
@cpriego Thank you, it solves the issue with the `$HOME`. However now I have a problem installing nginx, but I'm sure it is caused by valet instalation process.

**Comment by cpriego** [comment] 2017-04-06 04:39
@semencov try uninstalling and reinstalling valet with `valet uninstall` and `valet install`. By the way, now you can return to the stable release. If problems persist please open a new issue for a better follow up.

**Closed by cpriego** 2017-04-06 04:39 UTC

**Comment by semencov** [comment] 2017-04-06 06:53
@cpriego it wasn't needed. The problem with the nginx was caused by 3rd-party instalation. I've uninstalled the nginx, and `valet install` worked like a charm. Thanks for your help.
