### ISSUE TITLE
After installing Valet Linux I cannot navigate in internet

### ISSUE THREAD

**Issue by Acciaiodigitale** [cpriego/valet-linux#112] opened 2017-10-15 16:16 UTC
Antergos Linux
Valet v2.0.22

**Comment by cpriego** [comment] 2017-10-18 22:01
@CodelessFuture 

I am unable to reproduce that behavior, Antergos is precisely the flavor of Arch I'm using to test Valet functionality.

- Does the output of `systemctl status dnsmasq` has errors?
- Is the file `/opt/valet-linux/dns-servers` empty?
- Does the `/opt/valet-linux/resolv.conf` file have **only** `127.0.0.1` as its nameserver?
- Is `/etc/resolv.conf` a symlink to `/opt/valet-linux/resolv.conf`?

**Comment by toniwiki** [comment] 2017-10-31 10:59
Hi!!!

Same problem here with Manjaro 17.0.6 and Linux 4.14.0-1.

- dnsmasq says: "failed to access /opt/valet-linux/dns-servers: Not found". 

- And I have verified that it does not exist  ;-)

- /etc/resolv.conf is a symlink to /opt/valet-linux/valet-dns

**Comment by madaviela** [comment] 2017-11-08 16:04
i cant navigate after install and

Does the output of systemctl status dnsmasq has errors?
Is the file /opt/valet-linux/dns-servers empty?
Does the /opt/valet-linux/resolv.conf file have only 127.0.0.1 as its nameserver?
Is /etc/resolv.conf a symlink to /opt/valet-linux/resolv.conf? 

its fine except i have problems with dnsmasq i see cant find servers on /opt/valet-linux/dns-servers bt when i make cat on that file i see nameservers with 127.0.0.1.... please help

**Comment by victorsfleite** [comment] 2017-11-11 10:31
Same thing happened to me. I’ve just upgraded my Ubuntu from 17.04 to 17.10 and NetworkManager doesn’t seem to work properly after I installed valet.

First, I had a problem at valet installation: valet install command never ends, cause it can’t finish NetworkManager restart.

After I manually cancelled it, and restarted the computer, everything was working ok, except for the fact that some other apps couldn’t work properly when needing to use internet. Also, the computer isn’t shutting down properly, cause it never finishes trying to stop NetworkManager service. Sometimes the computer doesn’t even recognize wifi adapter.

Any help on that, please?

**Comment by sh4d1t0** [comment] 2017-11-13 20:18
Same problem here

**Comment by lembupeteng** [comment] 2017-11-15 05:43
just restart and solved

**Comment by mfehr94** [comment] 2017-11-21 18:40
use manjaro here. restart not working. 

    Does the output of systemctl status dnsmasq has errors? **No**
    Is the file /opt/valet-linux/dns-servers empty? **Yes except commented out stuff**
    Does the /opt/valet-linux/resolv.conf file have only 127.0.0.1 as its nameserver? **No such file**
    Is /etc/resolv.conf a symlink to /opt/valet-linux/resolv.conf? **No /etc/resolv.conf is a symlink to /opt/valet-linux/valet-dns**

**Comment by joshuamabina** [comment] 2017-11-23 05:39
I am experiencing the same problem running:

- Debian jessie
- Valet v2.0.22
- Nginx 1.12.2
- PHP 7.2.0RC5

#### Does the output of `systemctl status dnsmasq` has errors?

Answer: **No**

```
dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: active (running) since Thu 2017-11-23 07:57:51 EAT; 20min ago
  Process: 24287 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 24431 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 24395 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 24391 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 24430 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─24430 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
```

<hr>

#### Is the file /opt/valet-linux/dns-servers empty?

Answer: **Yes**

<hr>

#### Does the `/opt/valet-linux/resolv.conf` file have only 127.0.0.1 as its nameserver?

Answer: **No**

The contents of `/opt/valet-linux/resolv.conf` also include those in `/opt/valet-linux/valet-dns`. 

```
WORKDIR="/opt/valet-linux"
DNSFILE="${WORKDIR}/dns-servers"
DNSHEAD="${WORKDIR}/custom-nameservers"
LOGFILE="${WORKDIR}/watch.log"
VRESOLV="${WORKDIR}/resolv.conf"
RESOLV="/etc/resolv.conf"
function unique() {
    cat -n | sort -uk2 | sort -nk1 | cut -f2-
}

#...

exit 0 nameserver 127.0.0.1

```
<hr>

#### Is /etc/resolv.conf a symlink to /opt/valet-linux/resolv.conf?

Answer: **Yes**

**Comment by 37ch4** [comment] 2017-11-25 00:52
Hey guys. Not sure if this will work for anyone else but I simply installed valet had it up and running and the internet was not working. I then just ran "Valet Install" again and it updated correctly. I have the following in the  **/opt/valet-linux/dns-servers** file `nameserver 192.168.0.1`. Working in Manjaro.

**Comment by mfehr94** [comment] 2017-12-06 08:16
@37ch4 thanks works fine for me too.

**Comment by Vasiliy-Bondarenko** [comment] 2018-05-08 06:31
not working for me. ubuntu 18.04
after valet install resolve.conf points to /opt/valet-linux/valet-dns 
and there is no nameservers there. in besides this fie dir is empty. so i have to manually create 
dns-servers with name servers and now it start to work.

**Comment by david-dacruz** [comment] 2018-05-15 09:04
Hi @Vasiliy-Bondarenko I have the same issue and same ubuntu version I am not used to making all types of configurations and I would like not to mess it up, I have to reproduce the same steps as you could you explain more precisely pleasy how to manually create dns-servers with name server with valet-linux or maybe can you point to a trusted resource. Thanks ahead

**Comment by Vasiliy-Bondarenko** [comment] 2018-05-19 06:08
@david-dacruz you don't need to create it manually. it must be created after `valet install`. just put your nameservers in the file like
```
nameserver 1.1.1.1
nameserver 8.8.8.8
```

**Comment by vsimitsis** [comment] 2018-06-12 08:03
Ubuntu 18.04 having the same issue. Wifi seems always connected but i cant navigate. 2 out of 10 boots its working fine but at the rest 8 boots i just can't navigate and valet install or restarts doesn't help. Anyone found any solution? This thing destroys my mornings :(

**Comment by zdhz** [comment] 2018-06-13 11:00
@vsimitsis I've had the same issue on Ubuntu 18.04. The _temporary_ solution I've been using is to manually add Google's DNS to your `resolv.conf` file each time you boot up.

File: `/etc/resolv.conf/`
```
nameserver 127.0.0.1
nameserver 8.8.8.8
``` 

Hope this helps!

**Comment by jimmerioles** [comment] 2018-08-21 04:38
Got same problem with @joshuamabina 

Solved the issue with:
```bash
valet uninstall
valet install
```

**Comment by pedzed** [comment] 2018-08-30 09:45
@jimmerioles It works, but it does not seem to be persistent. When you reboot, you will lose the internet connection again.

**Comment by joshuamabina** [comment] 2018-08-30 15:50
@jimmerioles Unfortunately, still does not work for me.

@zdhz Nice! I have been forced to do the same. I wrote this  [script](https://github.com/joshuamabina/dotfiles/blob/master/bin/fixwifi.sh) to execute upon every boot to automagically fix the internet connection.

    #!/usr/bin/env bash

    FILENAME=/etc/resolv.conf

    if [ $(cat $FILENAME | grep -c "nameserver 1.1.1.1") -ne 0 ]; then
            echo "You are already browsing a faster, more private internet."
    else
            echo "nameserver 1.1.1.1" | sudo tee -a $FILENAME
    fi

If willing, you can make `/etc/resolv.conf` immutable to changes to the end of time. You can read [more](https://wiki.debian.org/resolv.conf) for more information and caveats on this.

**Comment by pedzed** [comment] 2018-08-30 15:52
@joshuamabina Ah, too bad you posted 6 hours later. I decided to ditch Valet and use a normal LEMP stack instead. Valet Linux does not really feel maintained to be honest.

**Comment by cjlaborde** [comment] 2018-09-14 01:50
> Thankfully i found this thread. I am trying to find what causes the problem 1 month now since i know few things about how those things work. I use LEMP for my dev environment.
> I have this issue at Ubuntu 18.04... Wifi seems always connected but i cant navigate. 2 out of 10 boots its working fine but at the rest 8 boots i just can't navigate and valet install or restarts doesn't help. Anyone found any solution? This thing destroys my mornings :(
Here is the solution to uninstall and fix DNS issues.
Follow this link
https://github.com/cpriego/valet-linux/issues/115

**Comment by jimmerioles** [comment] 2018-09-14 11:35
@pedzed @joshuamabina 

My usual workflow that works for me every time I start and end working using valet-linux is that I uninstall it when i'm done and reinstall it when starting.

That way it also keeps my machine clean and there's less programs running in the background and no additional scripts you need to run.

One thing that happens when doing this is it restarts the network manager so you need to wait a bit for your wifi connection to reconnect.

But this usually just takes less than 5 seconds to do both so that's not a problem with me.

**Comment by jimmerioles** [comment] 2018-09-14 15:13
@pedzed It is an option for a minimalist setup, and it's not really that a hassle. I doubt you'd be serving more than 3+ sites and working at them at the same time, at least that's the case with me.

And for me it's not "hackish", it is even more of a "minimalist" that way i'd only be running programs when needed and just serving sites that I actually going to be working on.

**Comment by pedzed** [comment] 2018-09-14 15:19
> And for me it's not "hackish", it is even more of a "minimalist"

Well, the fact that it is called `valet install` and `vallet uninstall` says that it is not supposed to be used as a power switch.

Anyway, I'm tired of Valet Linux. It used to be great, but I believe since the newer version of Ubuntu it just doesn't work well. Hence why I'd use a LEMP stack next time.

**Comment by jimmerioles** [comment] 2018-09-14 15:53
> Well, the fact that it is called valet install and vallet uninstall says that it is not supposed to be used as a power switch.

If you look at the underlying code and notice the behavior, it does not really uninstall stuff when running `valet install` and `valet uninstall`. It just enables/disables them (`dnsmasq`, `nginx`, etc..) so it does behave like a "power switch" :)

But I agree, this needs an active maintainer and fine tune things a bit.  And we can always send a pull request or fork it to solve our needs since this is a FOSS :)

**Comment by cjlaborde** [comment] 2018-09-16 06:27
This software almost made force me to having to reinstall linux. Since there were people with same issue.
I had to use google

> @vsimitsis I've had the same issue on Ubuntu 18.04. The _temporary_ solution I've been using is to manually add Google's DNS to your `resolv.conf` file each time you boot up.
> 
> File: `/etc/resolv.conf`
> 
> ```
> nameserver 127.0.0.1
> nameserver 8.8.8.8
> ```
> Hope this helps!

Had to use this solution to get back online and reinstall valet and leave it there till I manage to uninstall it months later. Was my worse experience I had this year with linux.

**Comment by railto** [comment] 2018-10-29 18:07
Just ran into this myself, to resolve it I had to remove the /etc/resolv.conf symlink and then create a new file for /etc/resolv.conf with a nameserver in it.

**Comment by railto** [comment] 2018-10-29 18:13
Run into same issues, when I uninstall valet it screws up my dnsmasq config, when i enable it again then everything works

**Comment by stefano-b** [comment] 2019-03-13 10:14
I'm having this issue as well, I'm reporting this from openSUSE.
When Valet is installed, I can't access internet.

I've tried some of the workarounds posted here, without any success.

Is there a chance that this will be fixed?

**Comment by pedzed** [comment] 2019-03-13 22:21
> Is there a chance that this will be fixed?

If you read my last comment, you could assume yes, there is a chance: about 1%.

**Comment by CitizenBeta** [comment] 2019-03-15 17:24
I'm having this issue on Ubuntu 18.04. Is there a solution to getting Valet working? After valet install, no websites will load.

**Comment by robmellett** [comment] 2019-03-18 01:24
Hey all, I had the issue this morning on Ubuntu 18.04.  It was because I accidentally installed composer as root.

`chown $USER /home/$USER/.composer/`

Globally Uninstal Valet with
`composer global remove cpriego/valet-linux`

Then reinstall with
`composer global install cpriego/valet-linux`

**Comment by beganovich** [comment] 2019-04-09 19:30
Issue is still there, Ubuntu 18 LTS.

**Closed** 2019-06-13 07:41 UTC

**Comment by lifeofdan** [comment] 2019-06-24 06:02
This issue still affects me.

**Comment by jmarcher** [comment] 2019-06-24 08:05
I need more information about each individual problem, better open a proper issue.

Although the problem may seem related, the origin may be different for each individual issue.

**Comment by CitizenBeta** [comment] 2019-06-24 13:44
My solution to this was to reformat my ubuntu machine and do a fresh install of Ubuntu. Not sure why/how that fixed the problem but a vanilla ubuntu install + valet worked. Same version of ubuntu as well. Not sure if that helps.

**Comment by CitizenBeta** [comment] 2019-06-24 13:47
The only thing I can think of is a collision with something else, perhaps either my Homestead stack (Vagrant/Virtualbox) and the associated dns stuff that it required OR a program like Skype that fiddles with ports OR my vpn. Also not sure why doing valet first fixed that, or maybe after reformatting using the latest version for sure of all three eliminated the problem.

**Comment by jmarcher** [comment] 2019-06-24 13:49
That was a radical solution :smile: 
Many people may not be aware that Apache is running in the background. 
But if someone is still having issues please open a new issue on GH all the information that you can gather.

**Comment by CitizenBeta** [comment] 2019-06-24 13:53
Yeah, but it didn't make sense why Valet was working for many others and not me so I figured a fresh install would eliminate the unknown. If not working on fresh 18.04 the problem belongs solely to Valet which seemed not the case. Based on my experience I'm not sure that this is a problem with Valet but rather another service being funky with the DNS changes.

**Comment by lifeofdan** [comment] 2019-06-24 23:08
Sorry for the lack of a useful post. Let me rectify that. :)

I am on OpenSUSE Tumbleweed. I have used Valet successfully on Ubuntu, I have also had this same network issue on Ubuntu. Like the previous poster, I also had to do a fresh install to get it working once. However, I'm not keen to do that at the moment. :) I have tried installing this both before and after installing Private Internet Access, both times I was unsuccessful. 

cat /opt/valet-linux/dns-servers returns
```
nameserver 209.222.18.222
nameserver 209.222.18.218
nameserver 1.1.1.1
```
cat /opt/valet-linux/resolv.conf returns
` nameserver 127.0.0.1`
ls -al of my /etc/ folder shows that opt/valet-linux/resolv.conf is symlinked to resolv.conf

doing a systemctl status dnsmasq returns 
```
● dnsmasq.service - DNS caching server.
   Loaded: loaded (/usr/lib/systemd/system/dnsmasq.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-06-25 09:02:07 AEST; 3min 37s ago
  Process: 16783 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 16784 (dnsmasq)
    Tasks: 1 (limit: 4915)
   Memory: 680.0K
   CGroup: /system.slice/dnsmasq.service
           └─16784 /usr/sbin/dnsmasq --log-async --enable-dbus --keep-in-foreground
```
I have tried restarting network.service, dnsmasq.service restarting my computer. All to no avail. Any help would be appreciated, as I do enjoy Valet when it is working. :)

**Comment by JunaidQadirB** [comment] 2019-08-05 07:37
Having the same issue on my fresh Ubuntu 19.04 install with `valet-linux`.

I have to manually change `nameserver` to `1.1.1.1` from `127.0.0.1` in  `/etc/resolv.conf`

Please fix the issue before the community ditch the project.

**Comment by silenoth** [comment] 2020-06-23 19:22
What is the solution then?

**Comment by cjlaborde** [comment] 2020-07-29 14:31
> Instalation destroy my internet connection, i can't rollback, what is the solution then?

I posted updated instructions here.
https://github.com/cpriego/valet-linux/issues/270

**Comment by songlineboy** [comment] 2021-01-23 05:56
will this be fixed?  

i installed on valet 2.2.19 on Ubuntu 20.04.01 > it broke the wifi.

I got it working in the end but following those steps in [270](https://github.com/cpriego/valet-linux/issues/270) - but is this issue going to be fixed? 

thanks

**Comment by YasienDwieb** [comment] 2021-07-15 00:32
The solution here works like a charm:
https://unix.stackexchange.com/a/163506/352826

**Comment by brantje** [comment] 2021-08-04 10:02
Still an issue of today. Devs please fix.

**Comment by vishy-experiments** [comment] 2022-03-26 08:51
This interim fix by one of the collaborators @jmarcher helped me. 
https://github.com/cpriego/valet-linux/issues/325#issuecomment-878102487

**Comment by danabrey** [comment] 2022-04-05 09:10
> This interim fix by one of the collaborators @jmarcher helped me. [#325 (comment)](https://github.com/cpriego/valet-linux/issues/325#issuecomment-878102487)

This does indeed stop the breakage in DNS after every reboot, however we then have to run `valet:install` after every reboot. I'm okay with that as an alternative to broken DNS, but this isn't a fix.

**Comment by joruizti** [comment] 2022-05-04 14:25
> Oigan todos,
> 
> No estoy seguro de si esto funcionará para alguien más, pero simplemente instalé el valet, lo tenía en funcionamiento y el Internet no funcionaba. Luego volví a ejecutar `valet install`y se actualizó correctamente. Tengo lo siguiente: **/opt/valet-linux/dns-servers** shows `nameserver 192.168.0.1` **/opt/valet-linux/resolv.conf** shows`nameserver 127.0.0.1`
> 
> Trabajando en Manjaro.

Funcionó para mi en arch

**Comment by sohailahmad07** [comment] 2022-06-14 08:43
> @CodelessFuture
> 
> I am unable to reproduce that behavior, Antergos is precisely the flavor of Arch I'm using to test Valet functionality.
> 
> * Does the output of `systemctl status dnsmasq` has errors?
> * Is the file `/opt/valet-linux/dns-servers` empty?
> * Does the `/opt/valet-linux/resolv.conf` file have **only** `127.0.0.1` as its nameserver?
> * Is `/etc/resolv.conf` a symlink to `/opt/valet-linux/resolv.conf`?

> * Does the output of `systemctl status dnsmasq` has errors? NO, its Working Fine
> * Is the file `/opt/valet-linux/dns-servers` empty? No its have these DNS servers 
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 192.168.10.1
nameserver fe80::1%wlo1
nameserver fe80::1%2

> * Does the `/opt/valet-linux/resolv.conf` file have **only** `127.0.0.1` as its nameserver? Yes
> * Is `/etc/resolv.conf` a symlink to `/opt/valet-linux/resolv.conf`? Yes
